### ISSUE TITLE
Unrecoverable error when running first against a non-running site

### ISSUE THREAD

**Issue by jvliwanag** [skevy/graphiql-app#1]
Steps to recreate:
1. Open GraphiQL binary. Point it to a url that's currently not running.
2. Type in a syntactically valid graphql query: e.g. '{ a }'
3. Press the 'Play' button.
4. Start up your graphql server. Change the URL.
5. Re-run your query. Currently, no output is produced. On the JS console the following error appears:

```
Uncaught TypeError: Cannot read property 'getQueryType' of undefined -- bundle.js:27
```

Restarting the app doesn't help.

Workaround:

1. `rm -Rf ~/Library/Application\ Support/graphiql-app/`
2. Make sure you execute your queries against a running server

**Comment by skevy** [comment]
Interesting. I'll look into this. Thanks for reporting!

**Comment by KyleAMathews** [comment]
Ran into this as well.

**Comment by skevy** [comment]
Interesting that you guys are saying this is unrecoverable. I get the error (which happens in GraphiQL btw, not in my code), but as soon as I change the URL again (which refreshes the editor), I'm able to complete the query successfully. This is still failing hard for you guys even on the latest version?

**Comment by skevy** [comment]
In general though, I feel like we're running into this error: https://github.com/graphql/graphiql/issues/16

**Comment by skevy** [comment]
@KyleAMathews @jvliwanag just FYI this is released in https://github.com/skevy/graphiql-app/releases/tag/v0.2.0

**Comment by KyleAMathews** [comment]
Woot! It's working! Thanks! 
![screen shot 2015-09-05 at 2 25 20 pm](https://cloud.githubusercontent.com/assets/71047/9701366/0205663c-53da-11e5-8e3e-397f81f55607.png)

**Comment by skevy** [comment]
:+1:

**Comment by jvliwanag** [comment]
Took me a long time to check back on this. But everything's working great with the latest release! :+1:
