### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by sulliwane** [skevy/graphiql-app#10]
I downloaded the source (.tar.gz) entered directory and ```npm install && npm start``` and I get this:

![screenshot from 2015-11-17 13 45 16](https://cloud.githubusercontent.com/assets/1733686/11203758/1b7a936c-8d32-11e5-8657-fb05e682f11a.png)

Thanks for you suggestions :)

**Comment by KyleAMathews** [comment]
Was there any console errors? (Open the dev tools)

**Comment by sulliwane** [comment]
![screenshot from 2015-11-17 14 01 37](https://cloud.githubusercontent.com/assets/1733686/11203905/e5daf510-8d33-11e5-80ca-aab58d84e298.png)

**Comment by sulliwane** [comment]
I downloaded the source code from here: https://github.com/skevy/graphiql-app/releases

**Comment by KyleAMathews** [comment]
Try cloning. No idea if that makes a difference here but worth a shot.

**Comment by jvliwanag** [comment]
Hm. Maybe missed the `npm run build` step?

**Comment by sulliwane** [comment]
```
/Downloads/graphiql-app-0.3.1$ npm run build

> graphiql-app@0.1.0 build /home/victor/Downloads/graphiql-app-0.3.1
> webpack --config webpack/webpack.config.production.js --progress --profile --colors

3256ms build modules      
10ms seal
3ms optimize 
118ms build modules       
15ms hashing
37ms create chunk assets
4783ms additional chunk assets
0ms optimize chunk assets 
0ms optimize assets 
Hash: 56a243faf9041bee1d56
Version: webpack 1.12.6
Time: 8268ms
    + 246 hidden modules

ERROR in ./app/mainApp.jsx
Module not found: Error: Cannot resolve module 'graphiql/graphiql.css' in /home/victor/Downloads/graphiql-app-0.3.1/app
 @ ./app/mainApp.jsx 7:0-32

ERROR in ./app/components/App.js
Module not found: Error: Cannot resolve module 'graphiql/dist' in /home/victor/Downloads/graphiql-app-0.3.1/app/components
 @ ./app/components/App.js 38:20-44
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

**Comment by sulliwane** [comment]
@KyleAMathews I tried cloning master, ```npm install && npm start``` , same blank window

**Comment by skevy** [comment]
@sulliwane i'm sure we can get this fixed. I don't have a linux dev env, so I'll have to spin up a VM. But I can work on this either today or tomorrow.

**Comment by sulliwane** [comment]
@skevy great, If I can be helpful in any way, just tell me.

**Comment by Solowave** [comment]
I believe I am having a similar issue if not the same on windows. Should all I have to do is clone, npm install, npm start?(with a npm run build?) I get errors on install/build and when I do npm start it opens a blank graphiql window.  If you need me to post errors or anything else just let me know

**Comment by sulliwane** [comment]
I solved the problem by running the app on mac, and then copy the content of dist folder (two files: bundle.js and main.css) from mac computer to my linux computer (same folder). It's these two files that can't get created on npm build (error).

**Comment by Solowave** [comment]
Ahh, I have no mac available. Hopefully there might be another fix

**Comment by sulliwane** [comment]
[dist.zip](https://github.com/skevy/graphiql-app/files/63598/dist.zip)

**Comment by Solowave** [comment]
Hey man thanks so much!  Spent so long yesterday trying to fix it.  Just a note when I npm run build I am still getting the errors cannot resolve module 'graphiql/graphiql.css' or graphiql/dist.  But as long as its working I'm happy.  This fix should probably be put in the read me for windows/linux users

**Comment by tinnou** [comment]
I'm having the same exact issue and I'm on a mac @skevy. The workaround only allows us to run the app from source but we still can't change the source itself as we are overwriting the `bundle.js` file. I tried with node v4.24 and v5.3.0

**Comment by tinnou** [comment]
Ok i think i found the reason. This commit https://github.com/skevy/graphiql-app/commit/1e4700b2e201967b2db515fa20a3b3def4f3e275 replaced back some dependencies on graphiQL. Replacing from `"skevy/graphiql#redbox"` to `"^0.3.0"` and re-run `npm install` and `npm run build` did the trick for me.

**Comment by skevy** [comment]
I'm going to be working on getting this app into a more maintainable state in the near future.

Hopefully that will resolve the issues people are running into on this thread. Sorry for all the trouble.

**Comment by F21** [comment]
Just tried building on Ubuntu 15.10 with nodejs 5.5.0 and ran into the same problem as @sulliwane:

```
user@ubuntu:~/Desktop/graphiql-app$ npm run build

> graphiql-app@0.1.0 build /home/user/Desktop/graphiql-app
> webpack --config webpack/webpack.config.production.js --progress --profile --colors

3958ms build modules      
14ms seal
5ms optimize 
147ms build modules       
12ms hashing
52ms create chunk assets
5673ms additional chunk assets
0ms optimize chunk assets 
1ms optimize assets 
Hash: 40985d223eccf14fc9e9
Version: webpack 1.12.12
Time: 9914ms
    + 246 hidden modules

ERROR in ./app/mainApp.jsx
Module not found: Error: Cannot resolve module 'graphiql/graphiql.css' in /home/user/Desktop/graphiql-app/app
 @ ./app/mainApp.jsx 7:0-32

ERROR in ./app/components/App.js
Module not found: Error: Cannot resolve module 'graphiql/dist' in /home/user/Desktop/graphiql-app/app/components
 @ ./app/components/App.js 38:20-44
Child extract-text-webpack-plugin:
        + 2 hidden modules
```

**Comment by mathieumg** [comment]
Same issue here with `master`. Ubuntu 14.04 x64 and Node 0.10.

**Comment by vshy108** [comment]
Ubuntu 15.10 x64, node 5.5.0,
I success to make it work.
npm install, npm run build, 
then replace the main.css and bundle.js inside dist/ folder with 
dist.zip from
@sulliwane commented on Dec 16, 2015
Thank you.

**Comment by GuillaumeLeclerc** [comment]
It works fine on my Linux setup with the current master branch

- clone
- `npm install`
- `npm run build`
- `npm run start`
