### ISSUE TITLE
Modifying HTTP Headers

### ISSUE THREAD

**Issue by Dermah** [skevy/graphiql-app#11]
It would be handy to be able to edit the keys and/or values of the existing HTTP headers, without having to delete and re-enter both key and value. 

I'm trying to add this feature on my own fork, but I haven't been able to get the app to start yet. I managed to get it building by `npm link`ing to a freshly cloned `graphiql` repository but the app throws an error when it trying to load the `QueryEditor`. Not sure what I'm doing wrong, any idea how I could work around that?

**Comment by skevy** [comment]
I hear you on this. I want it myself.

I'm planning to work on rewriting this into something more maintainable in the near future (I wrote the version that exists now in about an hour after GraphiQL first came out). So hopefully that will solve this (and other) issues. :)

**Comment by rmosolgo** [comment]
Has this been addressed? I'm happy with the current editing situation, anyways :) 

![image](https://cloud.githubusercontent.com/assets/2231765/26600487/4cfc4c92-454a-11e7-9df8-201b9d0be21c.png)

**Comment by skevy** [comment]
@andrefgneves added this feature in Sept! Closing this. :)
