### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by joshmanders** [skevy/graphiql-app#118]
From the **v0.7.0** to the **v0.7.1** the switch to `isomorphic-fetch` to `https` module has made it so self signed certificates for local development urls error out.

> Error: unable to verify the first certificate

**Comment by gjtorikian** [comment]
@craig-day Would you be able to look into this please?

**Comment by craig-day** [comment]
Sure thing. I’ll look at this tomorrow.

**Comment by craig-day** [comment]
@joshmanders do you have an example reproduction? There are a few possible ways errors like this can be resolved. We can required the appropriate root certificates, which is safe, or we can just tell the https library to ignore these errors but that is less secure. If you have an example it would be nice to test with.

**Comment by joshmanders** [comment]
@craig-day no example really, I use a tool called Valet (https://github.com/laravel/valet) and it secures local apps for development with self-sign certificates, previous version worked fine for these certificates, new version errors out, as I believe a self-signed certificate is not a valid certificate.
