### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nanandn** [skevy/graphiql-app#121]
I just installed 0.7.2 version. Doesn't work. Doesn't load the shema. 'Edit HTTP headers' doesn't do anything. 

The same URL (http://localhost:8080/graphiql) works in the browser.  Any idea why this app won't work?
![screen shot 2018-04-05 at 1 43 18 pm](https://user-images.githubusercontent.com/1680655/38390927-9b34762e-38d7-11e8-9c10-421639a8a860.png)

**Comment by gjtorikian** [comment]
Please try updating and see if that fixes the issue. The latest version is 0.7.2.

**Comment by nanandn** [comment]
I am using 0.7.2
I tried uninstall and re-install. Trird installimg using brew and the dmg image. 

Same problem.

**Comment by ZeroSoulEater** [comment]
Your endpoint needs to be graphql not graphiql

**Comment by nanandn** [comment]
Cool. That works. Since the endpoint was graphiql in the browser, I was using that. 
"graphql" works. 

Thanks
Anand

**Comment by nanandn** [comment]
However, GET is not working. Only POST works. Get gives me an error "java.lang.RuntimeException: variables should be either an object or a string"

**Comment by ZeroSoulEater** [comment]
I mad the same mistake, graphiql is only the url for the website. The graphiql website just use as default endpoint `/graphql` and the electron app let you choose your owen endpoint.

Yeah Graphql only supports POST requests
