### ISSUE TITLE
Blocked from opening on macOS because app is not from an identified developer

### ISSUE THREAD

**Issue by aergonaut** [skevy/graphiql-app#130]
It would be great if the app could be signed so that installing on macOS would not raise security warnings.

Background: I'm trying to bring GraphQL to my company, and I want to be able to point people at a good GraphQL explorer tool. I really like that this app can also specify headers to be included in the request, because we are securing our GraphQL API with API keys. However, our machines have stricter security settings that prevent us from installing unsigned apps.

It would be great if the app could be signed so that my team and I could install it!

**Comment by gjtorikian** [comment]
I think signing requires one to be an official developer, right? And that costs money. And this is an entirely volunteer run effort. 

I understand the "work has locked stuff down" problem--believe me--but I don't know that anyone working on the project is a member and would be willing to sign the app indefinitely. 

Could you possibly recompile the code and sign it yourselves to distribute it at work?

**Comment by aergonaut** [comment]
That's a good idea. I can try doing that.

**Comment by aergonaut** [comment]
Actually it appears that, for some reason, installing using `brew cask` bypasses the Gatekeeper restrictions on our machines. So I can recommend my team use `brew cask` to install this instead of downloading from GitHub.

**Comment by harsha-sagar** [comment]
@aergonaut 
installed using `brew cask`, but stilling same issue.

**Comment by marunk20** [comment]
installed using `brew cask` .. but still getting the same error

**Comment by kingkarki** [comment]
Go to the System Preferences -> Privacy & Security. You will find list of the blocked apps there. Click open and allow it. Thats it.
