### ISSUE TITLE
Deadware??

### ISSUE THREAD

**Issue by sjmcdowall** [skevy/graphiql-app#139]
@skevy -- Is this pretty much deadware? Are you no longer supporting this?  I ask because there are 4 PR's outstanding for some time and no changes in about a year and the issues are stacking up.  Perhaps you should add more "maintainers" etc. to keep this thing moving?

**Comment by gjtorikian** [comment]
It isn't deadware. I was added some time ago. We're all just quite busy.

The app works good enough for most people, I suspect.

**Comment by skevy** [comment]
To echo Garen — I use this at work literally every single day. It’s not deadware. If it was broken, I would fix it. There are other more full-featured GraphiQL wrappers out there — Insomnia, GraphQL Playground, etc. You should feel free to use those if you don’t like the what this one offers, or you can fork if we’re not responding to PRs fast enough.

**Comment by sjmcdowall** [comment]
@skevy -- If I didn't care or like this I wouldn't have taken the time to ask about it.  I am glad to see y'all are still active and on top of this -- if the speed of responses to this issue is any indication. :)  Cheers!

**Comment by gjtorikian** [comment]
Appreciated, @sjmcdowall.
