### ISSUE TITLE
Unmaintained?

### ISSUE THREAD

**Issue by jmahhh** [skevy/graphiql-app#160]
Is this project still maintained? #154 is making this effectively unusable.

**Comment by memark** [comment]
Maybe @skevy has some information?

**Comment by skevy** [comment]
@jmahhh this project is not really "unmaintained" so much as "it's working for me".

If you would like to see #154 fixed, maybe you should send me a PR?

I don't use Linux on the desktop, and have no plans to. Any support for Linux needs to be community maintained.
