### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by KyleAMathews** [skevy/graphiql-app#17]
@kevinold @skevy should we make a new release? Especially with the new Brew Cask integration.

**Comment by kevinold** [comment]
I need to fix one more bug. Seeing an error when launching the latest build. Will get a fix in the next few days.

**Comment by kevinold** [comment]
Or if you're able to fix go for it @KyleAMathews. As soon as you launch it you'll see in the results panel.

**Comment by KyleAMathews** [comment]
:+1: probably won't get to it. Got to get Gatsby in ship-shape for React conf!
