### ISSUE TITLE
Does not have instruction for Windows installation.

### ISSUE THREAD

**Issue by EugeneGohh** [skevy/graphiql-app#190]
I found that `README.md` doesn't have the installation for Windows. It's a total frustration since I don't know how to install it for the first time.

**Comment by hanancs** [comment]
Why did you close it buddy? Waiting is so hard but worth it 😂

**Comment by hanancs** [comment]
Click below the link and you can find the exe for windows. 
https://github.com/skevy/graphiql-app/releases

**Comment by EugeneGohh** [comment]
> Why did you close it buddy? Waiting is so hard but worth it 😂

This probably not an active repo decided to close it for good.
