### ISSUE TITLE
When changing tabs your query stays the same

### ISSUE THREAD

**Issue by standayweb** [skevy/graphiql-app#20]
When you switch tabs or add a new tab it only allows one query between tabs, you should be able to have different queries open.

**Comment by holmesal** [comment]
Seeing this as well - there is currently only one query, shared by all tabs - changes made in one tab apply to other tabs as well.

**Comment by lucasbento** [comment]
This doesn't appear to be happening anymore.

I think we can close this.

cc @skevy.

**Comment by skevy** [comment]
Awesome! Yah I fixed this in 0.4.2
