### ISSUE TITLE
Introspection query should be updated to include Subscriptions

### ISSUE THREAD

**Issue by vning93** [skevy/graphiql-app#35]

**Comment by skevy** [comment]
Pretty sure this is good now -- needed to update to the latest GraphiQL version.

**Comment by zackify** [comment]
Subscriptions don't seem to work still, in apollo on the default graphiql I am adding:
```
app.use(
  '/graphiql',
  graphiqlExpress({
    endpointURL: '/graphql',
    subscriptionsEndpoint: 'ws://localhost:8888/subscriptions',
  })
);
```

Don't see a way to give this app the subscription url?
