### ISSUE TITLE
Error on `npm start`

### ISSUE THREAD

**Issue by sibelius** [skevy/graphiql-app#38]
I'm receiving this error when I try to run using `npm start`

`/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-9.1.12/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 3 `

I'm using node 6.2.1, on macosx El Captain

**Comment by sibelius** [comment]
running `npm run build` before worked

**Comment by jarjis** [comment]
can please share what fixed the issue ?

**Comment by sibelius** [comment]
Make sure ur URL has http:// in the beginning

**Comment by slavikshen** [comment]
I have the same issue

/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-10.1.5/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display 4 


The urls are right.  But the electron just fail.  And it seem that the console.log is not working even with --enable-logging

I guess something must be wrong before the loading code.
