### ISSUE TITLE
Variables are invalid JSON

### ISSUE THREAD

**Issue by sibelius** [skevy/graphiql-app#48]
I'm receiving the error: `Variables are invalid JSON.` when I try to use the following mutation

```graphql
mutation deployChain {
 Deploy(input: {
  fcn:"init"
  args: ["a", "100", "b", "200"]
  clientMutationId:"1"
	}) {
  	results
	}
}
```

```jsx
BadRequestError: Variables are invalid JSON.
  at parseGraphQLParams (app/node_modules/express-graphql/dist/index.js:254:38)
at app/node_modules/express-graphql/dist/index.js:234:12
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

The same mutation works fine on browser

**Comment by bswinnerton** [comment]
👋 @sibelius,

Is is possible you have a malformed set of variables in the "Query Variables" section of GraphiQL?

**Comment by sibelius** [comment]
hard error to debug, tks for ur response

there were some old variable inside "Query Variables" tks
