### ISSUE TITLE
403 The origin "null" is not authorized

### ISSUE THREAD

**Issue by intellix** [skevy/graphiql-app#53]
Our API server implements CORS where we whitelist particular Origin headers. GraphiQL App is sending an `origin` of `null` which means we can't whitelist this application in particular.

Each time I work on our API I just have to disable CORS and it would be nice if GraphiQL App at least provided something here.

**Comment by intellix** [comment]
Related: https://github.com/electron/electron/issues/7931

**Comment by skevy** [comment]
I don't have a use case for this specifically, but if you want to send a PR, I'd be glad to merge it!
