### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by MichelDiz** [skevy/graphiql-app#59]
I'm trying to use your project at windows 10.
> npm install
> npm start

But get errors.

Best regards

**Comment by Mifrill** [comment]
try npm run build

**Comment by jaaaco** [comment]
I needed version for windows, too. I prepared binary release:

https://github.com/jaaaco/graphiql-app/releases/tag/v0.5.1b

Plz let me know if Windows version are working ok (I couldn't check them on Wine)

**Comment by Mifrill** [comment]
Jaaaco, graphiql-app-win32-x64.zip - working perfectly

**Comment by skevy** [comment]
Please use the release version: https://github.com/skevy/graphiql-app/releases

**Comment by cfjedimaster** [comment]
I know this is closed, but the readme for the project mentions macOS and Linux only. I assumed that maybe something in the codebase made it not work in Windows. Even if it's unofficial, should the project's readme at least mention it?

**Comment by I-keep-trying** [comment]
> I know this is closed, but the readme for the project mentions macOS and Linux only. I assumed that maybe something in the codebase made it not work in Windows. Even if it's unofficial, should the project's readme at least mention it?

Nobody cares about Windows. 😥

**Comment by marcusjwhelan** [comment]
@I-keep-trying except when your company requires you to work on windows.
