### ISSUE TITLE
Brew GraphiQL App not working

### ISSUE THREAD

**Issue by LucasRettig** [skevy/graphiql-app#63]
My GraphiQL brew app is not working.  It just sits and clocks.  I am getting the following error:
![image](https://cloud.githubusercontent.com/assets/15785789/26729979/14318198-4775-11e7-9b19-19d5bad88841.png)

I tried updating brew and reinstalling and still get the same errors.

Have you guys seen this before?

**Comment by skevy** [comment]
Waiting for this to be merged: https://github.com/caskroom/homebrew-cask/pull/35648

It should work at that point.

**Comment by skevy** [comment]
Go ahead and give the latest Cask a try @LucasRettig :)

**Comment by LucasRettig** [comment]
This works now.  Thanks @skevy !
