### ISSUE TITLE
how to close a query tab ?

### ISSUE THREAD

**Issue by sunthx** [skevy/graphiql-app#70]
tks

**Comment by gjtorikian** [comment]
On a Mac, it is <kbd>⌘+w</kbd>. On Windows/Linux, it's <kbd>Control+w</kbd>, I believe. 

You can also go to `File -> Close Query` in the menu bar.

**Comment by sunthx** [comment]
i installed the latest version (0.6.0) on windows.

-  `File -> Close Query` not found in the menu bar.
- <kbd>control + w </kbd> not working.

tks.

**Comment by sunthx** [comment]
tks. @gjtorikian @shiftkey
