### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by colllin** [skevy/graphiql-app#77]
I'm not sure where to go from here...  just downloaded v0.6.0 and haven't seen a successful request yet.

<img width="1038" alt="screen shot 2017-07-27 at 12 20 48 pm" src="https://user-images.githubusercontent.com/185923/28685759-0ec4b938-72c6-11e7-9405-008d4305ef46.png">

**Comment by skevy** [comment]
This is your API returning a bad response -- this isn't a GraphiQL issue.

**Comment by colllin** [comment]
Thanks!

**Comment by ryannealmes** [comment]
Getting the same issue. I can get things working on normal localhost graphiql, but as soon as I try this ... no luck.

**Comment by gjtorikian** [comment]
> This is your API returning a bad response -- this isn't a GraphiQL issue.

**Comment by itsnothingg** [comment]
having same problem here

**Comment by danaki** [comment]
GraphQL 0.7.2. Confirm similar error but no requests to investigate in the Network tab. I understand this is my application error but can't check the output because Graphiql app is the only option to set JWT authorization header. Please make this output available even if JSON can't be parsed.
