### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by Malax** [skevy/graphiql-app#79]
Hey!

I was having an issue with CORS requests and saw that #66 fixed it. 👍 
However, there is no release where the issue has been fixed. Would it be possible to release a new version with the fixes? I currently use a clone of this repo to start the fixed version, but that does not feel right. :)

Thank you!

**Comment by gjtorikian** [comment]
Done! https://github.com/skevy/graphiql-app/releases/tag/v0.6.1

**Comment by Malax** [comment]
Thank you very much! :)
