### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by sithadmin** [skevy/graphiql-app#81]
Windows 10
Opening the same URL in Chrome works
Graphiql-app 0.61

**Comment by gjtorikian** [comment]
What's the URL?

**Comment by sithadmin** [comment]
sorry.. http://localhost:3000/graphiql

**Comment by jessitron** [comment]
@sithadmin I saw this error today, and it was an HTML response from the graphql server.

 If you go to View-> Toggle Developer Tools, and then hit refresh, you might see a red network request. If you look at the response, you might see a meaningful error in the HTML.

**Comment by sithadmin** [comment]
No errors reported in Dev Console.  And a normal browser displays the content correctly.

**Comment by gjtorikian** [comment]
Ah, are you trying to embed GraphiQL into a site? If so, https://github.com/graphql/graphiql may be the repository you want. 

This repository is for a stand-alone app that makes use of the same GraphiQL. But it's not meant (or even possible) to run on a website.

**Comment by sithadmin** [comment]
@gjtorikian I know this is a standalone app, I am currently following a Youtube playlist [here](https://www.youtube.com/watch?v=2mXUcBHoJcA&list=PLzQWIQOqeUSM51q7ZIqvDQ-Myp58IVPEN&index=6) and the author is able to use this app to talk to his GraphiQL setup, but I am not.  Other than the differences in OS, I don't think my setup is that much different.

**Comment by sithadmin** [comment]
Well, I must apologize.  This was user error.  I will write this up to my inexperience with GraphQL.  I was pointing to the web front-end, not the endpoint.  Sorry to bother everyone.  I'll go stand in the corner now and think about what I've done...
