### ISSUE TITLE
Help menu (MacOS) broken

### ISSUE THREAD

**Issue by philwareham** [skevy/graphiql-app#84]
Hi,

Very handy app!

On MacOS (version tested 10.12.6) when I select any of the 4 options in the GraphiQL app (version 0.6.1) help menu I get messages such as the following:

![grab1](https://user-images.githubusercontent.com/413665/31428165-cc063b4e-ae61-11e7-836c-7b7de8eb0617.png)

**Comment by samthomson** [comment]
I can reproduce this bug.

**Comment by philwareham** [comment]
Just a further note: Latest version (0.6.3) fixes the error above but all help currently points to the Electron project not specifically the GraphiQL app project's pages. Cheers!
