### ISSUE TITLE
Operation name dropdown causing weird overflow

### ISSUE THREAD

**Issue by lsmith130** [skevy/graphiql-app#94]
<img width="453" alt="screen shot 2017-10-24 at 7 26 57 pm" src="https://user-images.githubusercontent.com/2815712/31975959-cbb7caa0-b8f1-11e7-9e45-3b53a475df96.png">

This happened on two different macs when updating to 0.6.3. I've downgraded to 0.6.1 and it's working as normal again. It's possible to select options by scrolling the header bar, but it's severely hampering the UX. If I had more time I'd look at fixing it myself, but I'm swamped right now. Thanks!!

**Comment by 0ff** [comment]
Same here, downgrade worked as well. Hopefully this can be addressed in the next version.
