### ISSUE TITLE
`brew cask install [...]` installs outdated version on OSX

### ISSUE THREAD

**Issue by samlevin** [skevy/graphiql-app#97]
```
$ brew cask install graphiql
==> Downloading https://github.com/skevy/graphiql-app/releases/download/v0.6.1/graphiql--0.6.1.zip
```

**Comment by xiaoyu860519** [comment]
二

**Comment by gjtorikian** [comment]
I suspect a local issue; the [cask was bumped to 0.6.3](https://github.com/caskroom/homebrew-cask/pull/39997) some time ago.

**Comment by gjtorikian** [comment]
Closing as stale, please reopen if this is not correct.

**Comment by tosbourn** [comment]
I vote to close this issue - I've literally just ran this command and got the latest version.

**Comment by muzala** [comment]
Why is too difficult to get but am still try it if I get it well than is gonna be OK
